### ISSUE TITLE
作者您好，请问一下如何将本地读取改成直接读取服务器端的文件数据呢

### ISSUE THREAD

**Issue by lan-tianxiang** [batsing/csv2arr#1]
能够实现吗？谢谢

**Comment by batsing** [comment]
把csv2arr.js里的 fReader.onload = function(evt) 那部分改成从ajax获取数据就行了。

**Comment by lan-tianxiang** [comment]
嗯，谢谢

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Li Weijie ***@***.***&gt;;
发送时间：2021年7月7日(星期三) 上午9:48
收件人："batsing/csv2arr" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [batsing/csv2arr] 作者您好，请问一下如何将本地读取改成直接读取服务器端的文件数据呢 (#1)
-----------------------------------

 

 
把csv2arr.js里的 fReader.onload = function(evt) 那部分改成从ajax获取数据就行了。
